import React, { useEffect, useMemo, useState } from 'react';
import { BranchComparison, GraphPayload, GitRef, ViewMode } from '../domain/models'; import { vscode } from './vscode';

export function App() {
  const [data, setData] = useState<GraphPayload>(); const [comparison, setComparison] = useState<BranchComparison>(); const [error, setError] = useState('');
  const [tags, setTags] = useState(true), [remotes, setRemotes] = useState(false), [filter, setFilter] = useState(''); const [selected, setSelected] = useState<GitRef>();
  useEffect(() => { const fn = (e: MessageEvent) => { if (e.data.type === 'graph') setData(e.data.payload); if (e.data.type === 'comparison') setComparison(e.data.payload); if (e.data.type === 'error') setError(e.data.message); }; addEventListener('message', fn); return () => removeEventListener('message', fn); }, []);
  const allowed = useMemo(() => new Set((data?.refs ?? []).filter(r => (tags || r.type !== 'tag') && (remotes || r.type !== 'remoteBranch') && (!filter || r.name.toLowerCase().includes(filter.toLowerCase()))).map(r => r.fullName)), [data, tags, remotes, filter]);
  if (!data) return <main className="loading"><div className="spinner"/><h2>Reading commit topology…</h2>{error && <p className="error">{error}</p>}</main>;
  const refs = data.refs.filter(r => allowed.has(r.fullName));
  return <div className="app"><header><div className="brand"><span className="mark">⌁</span><div><strong>Git Topology</strong><small>{data.repository}</small></div></div><div className="modes">{(['topology','compact','full'] as ViewMode[]).map(m => <button key={m} className={data.mode === m ? 'active' : ''} onClick={() => vscode.postMessage({type:'setViewMode',mode:m})}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><button className="refresh" onClick={() => vscode.postMessage({type:'refresh'})}>↻ Refresh</button></header>
    <div className="filters"><label><input type="checkbox" checked readOnly/> Local branches</label><label><input type="checkbox" checked={tags} onChange={e=>setTags(e.target.checked)}/> Tags</label><label><input type="checkbox" checked={remotes} onChange={e=>setRemotes(e.target.checked)}/> Remote branches</label><input className="search" placeholder="Filter branches…" value={filter} onChange={e=>setFilter(e.target.value)}/><span>{data.graph.nodes.filter(n=>n.kind==='commit').length} nodes · {refs.length} refs</span></div>
    <div className="content"><Graph data={data} allowed={allowed} onSelect={setSelected}/><aside><Inspector selected={selected} refs={refs} comparison={comparison} onClose={()=>setSelected(undefined)}/></aside></div>{error && <div className="toast">{error}</div>}</div>;
}
function Graph({data, allowed, onSelect}:{data:GraphPayload;allowed:Set<string>;onSelect:(r:GitRef)=>void}) {
  const commits = new Map(data.graph.nodes.filter(n=>n.commit).map(n=>[n.id,n])); const maxX=Math.max(800,...data.graph.nodes.map(n=>n.x+300)), maxY=Math.max(600,...data.graph.nodes.map(n=>n.y+100));
  return <section className="canvas"><svg width={maxX} height={maxY}>
    <g className="edges">{data.graph.edges.map((e,index)=>{const a=commits.get(e.from),b=commits.get(e.to);if(!a||!b)return null;return <path key={`${e.from}:${e.to}:${index}`} d={`M ${a.x} ${a.y} C ${a.x} ${(a.y+b.y)/2}, ${b.x} ${(a.y+b.y)/2}, ${b.x} ${b.y}`} />})}</g>
    {data.graph.nodes.map(n=>n.kind==='range'?<g key={n.id} className="range" transform={`translate(${n.x},${n.y})`} onClick={()=>vscode.postMessage({type:'expandRange',rangeId:n.id})}><rect x="-8" y="-17" width="118" height="34" rx="17"/><text x="10" y="5">+{n.range!.count} commits</text></g>:<g key={n.id} className="node" transform={`translate(${n.x},${n.y})`}><circle r={n.commit!.refs.length?8:6}/><text className="sha" x="18" y="5">{n.id.slice(0,7)}</text>{n.commit!.refs.filter(r=>allowed.has(r.fullName)).map((r,i)=><g key={r.fullName} className={`ref ${r.type}`} transform={`translate(${78+i*120},-14)`} onClick={()=>onSelect(r)}><rect width="112" height="28" rx="5"/><text x="9" y="19">{r.type==='tag'?'◆ ':r.type==='remoteBranch'?'☁ ':'⑂ '}{r.name.length>13?r.name.slice(0,12)+'…':r.name}</text></g>)}</g>)}
  </svg></section>;
}
function Inspector({selected,refs,comparison,onClose}:{selected?:GitRef;refs:GitRef[];comparison?:BranchComparison;onClose:()=>void}) {
  const [other,setOther]=useState(''),[mode,setMode]=useState<'divergence'|'snapshot'>('divergence');
  useEffect(()=>setOther(refs.find(r=>r.fullName!==selected?.fullName)?.fullName??''),[selected]);
  if (!selected) return <div className="empty"><span>⑂</span><h3>Select a branch or tag</h3><p>Inspect a ref, compare its history, and open file changes in the VS Code diff editor.</p></div>;
  const compare=()=>vscode.postMessage({type:'compareRefs',left:selected.fullName,right:other,mode});
  return <div className="inspector"><button className="close" aria-label="Close inspector" title="Close inspector" onClick={onClose}>×</button><small>{selected.type.replace(/([A-Z])/g,' $1').toUpperCase()}</small><h2>{selected.name}</h2><code>{selected.commitId.slice(0,12)}</code><div className="actions"><button onClick={()=>vscode.postMessage({type:'copy',value:selected.name})}>Copy name</button><button onClick={()=>vscode.postMessage({type:'copy',value:selected.commitId})}>Copy SHA</button></div><hr/><h3>Compare with</h3><select value={other} onChange={e=>setOther(e.target.value)}>{refs.filter(r=>r.fullName!==selected.fullName).map(r=><option key={r.fullName} value={r.fullName}>{r.name}</option>)}</select><label className="radio"><input type="radio" checked={mode==='divergence'} onChange={()=>setMode('divergence')}/> Changes since divergence</label><label className="radio"><input type="radio" checked={mode==='snapshot'} onChange={()=>setMode('snapshot')}/> Current snapshots</label><button className="primary" disabled={!other} onClick={compare}>Compare refs</button>{comparison&&comparison.left===selected.fullName&&<Comparison value={comparison}/>}</div>;
}
function Comparison({value}:{value:BranchComparison}) { return <div className="results"><h3>Comparison</h3><div className="base"><small>MERGE BASE</small><code>{value.mergeBases[0]?.slice(0,9)??'None'}</code></div><div className="metrics"><div><b>+{value.ahead}</b><small>only left</small></div><div><b>{value.behind}</b><small>only right</small></div><div><b>{value.files.length}</b><small>files</small></div></div><p className="stat"><ins>+{value.additions}</ins> <del>−{value.deletions}</del></p><h3>Changed files</h3><div className="files">{value.files.map(f=><button key={`${f.status}:${f.oldPath ?? ''}:${f.path}`} onClick={()=>vscode.postMessage({type:'openDiff',left:value.left,right:value.right,path:f.path,oldPath:f.oldPath,status:f.status[0]})}><i className={f.status}>{f.status}</i><span>{f.path}</span></button>)}</div></div> }
